spring:
  datasource:
    url: jdbc:mysql://db:3306/bookdb
    username: bookuser
    password: bookpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

pricing:
  base-url: http://pricing-api:8082
